title: "Antti Käenmäki"
author: "Antti Käenmäki"
description: "Antti Käenmäki"
domain: anttikaenmaki.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://anttikaenmaki.github.io  # the base hostname and protocol for your site, e.g. http://example.com
baseurl: "/"      # place folder name if the site is served in a subfolder
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %e, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
show_description: false    # show the site description in the sidebar
show_excerpts: false       # show excerpts of the blog posts
minimal: false              # use a dark header
mathjax: true

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html", icon: home}
  - {file: "publications.md", icon: file}
  - {file: "teaching.md", icon: chalkboard-teacher}
  - {file: "blog.md", icon: comment}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:antti.kaenmaki@gmail.com"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
